# 路径: ./build_exe.py
# 作用: 一键生成 requirements.txt、转换图标并使用 PyInstaller 打包为 onedir Windows 程序

from __future__ import annotations

import importlib.metadata as md
import importlib.util
import os
import shutil
import subprocess
import sys
from pathlib import Path

PROJECT_NAME = "cc模型管理器"
ENTRY_POINT = "main.py"
EXAMPLE_CONFIG = "config.example.json"

# 代码里用到的运行时依赖 + 打包依赖
DEPENDENCIES = [
    "PyQt6",
    "PyQt6-Qt6",
    "PyQt6-sip",
    "psutil",
    "httpx",
    "socksio",
    "Pillow",
    "PyInstaller",
]


def project_root() -> Path:
    return Path(__file__).resolve().parent


def package_version(package_name: str) -> str:
    try:
        return md.version(package_name)
    except md.PackageNotFoundError:
        install_packages([package_name])
        return md.version(package_name)


def missing_packages(packages: list[str]) -> list[str]:
    missing: list[str] = []
    for package in packages:
        try:
            md.version(package)
        except md.PackageNotFoundError:
            missing.append(package)
    return missing


def install_packages(packages: list[str]) -> None:
    if not packages:
        return
    uv = shutil.which("uv")
    if uv:
        command = [
            uv,
            "pip",
            "install",
            "--python",
            sys.executable,
            *packages,
        ]
    elif importlib.util.find_spec("pip") is not None:
        command = [sys.executable, "-m", "pip", "install", *packages]
    else:
        raise RuntimeError(
            "当前虚拟环境缺少 pip，系统中也未找到 uv。"
            "请先安装 uv，或运行 python -m ensurepip。"
        )
    subprocess.run(command, check=True)


def ensure_dependencies(packages: list[str]) -> None:
    missing = missing_packages(packages)
    if missing:
        print(f"[INFO] 正在安装缺失依赖：{', '.join(missing)}")
        install_packages(missing)


def generate_requirements(req_path: Path) -> list[str]:
    lines: list[str] = [
        "# Auto-generated by build_exe.py",
        "# 运行时与打包依赖均按当前环境已安装版本写入",
        "",
    ]

    for package in DEPENDENCIES:
        version = package_version(package)
        lines.append(f"{package}=={version}")

    req_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return lines


def convert_webp_to_ico(webp_path: Path, ico_path: Path) -> None:
    from PIL import Image

    if not webp_path.exists():
        raise FileNotFoundError(f"未找到图标文件：{webp_path}")

    ico_path.parent.mkdir(parents=True, exist_ok=True)
    with Image.open(webp_path) as img:
        img = img.convert("RGBA")
        sizes = [(16, 16), (24, 24), (32, 32), (48, 48), (64, 64), (128, 128), (256, 256)]
        img.save(ico_path, format="ICO", sizes=sizes)


def cleanup_previous_build(root: Path) -> None:
    for name in ("build", "dist"):
        path = root / name
        if path.exists():
            shutil.rmtree(path, ignore_errors=True)

    spec_path = root / f"{PROJECT_NAME}.spec"
    if spec_path.exists():
        spec_path.unlink()


def build_pyinstaller_command(root: Path, icon_ico: Path) -> list[str]:
    entry_point = root / ENTRY_POINT
    if not entry_point.exists():
        raise FileNotFoundError(f"未找到入口文件：{entry_point}")

    command = [
        sys.executable,
        "-m",
        "PyInstaller",
        "--noconfirm",
        "--clean",
        "--onedir",
        "--windowed",
        "--name",
        PROJECT_NAME,
        "--icon",
        str(icon_ico),
        "--paths",
        str(root),
        "--add-data",
        f"{icon_ico};.",
    ]

    # PyQt6 的 hooks 一般足够，但显式收集子模块更稳妥
    command += [
        "--collect-all",
        "PyQt6",
        str(entry_point),
    ]
    return command


def copy_distribution_files(root: Path, dist_dir: Path) -> None:
    example_config = root / EXAMPLE_CONFIG
    if not example_config.exists():
        raise FileNotFoundError(f"未找到示例配置文件：{example_config}")
    shutil.copy2(example_config, dist_dir / EXAMPLE_CONFIG)


def main() -> None:
    if os.name != "nt":
        raise RuntimeError("该脚本面向 Windows 打包。")

    root = project_root()
    req_path = root / "requirements.txt"
    webp_icon = root / "icon.webp"
    ico_icon = root / "icon.ico"

    # 先确保用于打包的工具存在
    ensure_dependencies(["Pillow", "PyInstaller"])

    # 依赖版本写入 requirements.txt
    generate_requirements(req_path)

    # 转换图标
    convert_webp_to_ico(webp_icon, ico_icon)

    # 清理旧构建产物
    cleanup_previous_build(root)

    # 开始打包
    command = build_pyinstaller_command(root, ico_icon)
    print("[INFO] 开始执行打包命令：")
    print(" ".join(f'"{part}"' if " " in part else part for part in command))
    subprocess.run(command, check=True)

    dist_dir = root / "dist" / PROJECT_NAME
    copy_distribution_files(root, dist_dir)
    print(f"[OK] 打包完成：{dist_dir}")


if __name__ == "__main__":
    main()
